### ISSUE TITLE
Cannot download to the internal storage

### ISSUE THREAD

**Issue by sungwoncho** [sgrebnov/cordova-plugin-background-download#14]
I am using this plugin to download files to Android device's `/data/data/myAppName`, which is the path where the app is installed.

```
var downloader = new BackgroundTransfer.BackgroundDownloader();
var download = downloader.createDownload(uriString, targetFile);

download = download.startAsync().then(onSuccess, onError, onProgress);
...
```

However I get an exception:

    Destination must be on external storage

Any suggestions?

**Comment by mitriy** [comment]
+1 for this issue

**Comment by sungwoncho** [comment]
Yep. Thanks for the link. Resolved by downloading to external storage and copying to internal storage.

**Comment by igor9silva** [comment]
I have this same issue. Has anyone found a real solution?
Copying is not an option for me.
