### ISSUE TITLE
Concurrent downloads in iOS

### ISSUE THREAD

**Issue by TestVTeam** [sgrebnov/cordova-plugin-background-download#21]
Hello,

We are using this plugin for iOS app, but the One-File-at-a-time limitation is a really bother one.

Are there any chances of removing this limitation. It would be of great help.

Thanks!

**Comment by brodybits** [comment]
I have a quick fix at: https://github.com/brodybits/cordova-plugin-background-download/tree/cb-ios-concurrent-fix1

It includes the code from https://github.com/brodybits/TWRDownloadManager which is a fork with a couple fixes. Note that TWRDownloadManager has a different license (MIT).

I will fix my fork to include TWRDownloadManager as an external dependency when I get a chance.

**Comment by NickToropov** [comment]
Hi @TestVTeam, we've added support of concurrency for iOS in [PR#54](https://github.com/sgrebnov/cordova-plugin-background-download/pull/54).

I'll close this issue for now but feel free to reopen it if you have any questions.
