### ISSUE TITLE
Rename notification mesage "org.apache.cordova.backgroundDownload plugin" on downloading

### ISSUE THREAD

**Issue by arunap** [sgrebnov/cordova-plugin-background-download#30]
When downloading files using this plugin on Android, It shows "org.apache.cordova.backgroundDownload plugin" message on notification drawer. I changed the plugin line no `request.setTitle("org.apache.cordova.backgroundDownload plugin");` with a custom title, but it still shows the same message. Is there anyway to change this?

**Comment by MichaelApproved** [comment]
Changing that text worked for me. Remember that you need to either remove/add the plugin back in with the correct text or (I believe) remove the platform and re-add it. Without one of those steps, the platform will retain the old code from the plugin.

**Comment by posti85** [comment]
Anyway, configuring that title or just showing the name of the file being downloaded, it is more 	presentable than a static string with the name of the plugin...

**Comment by NickToropov** [comment]
Hi guys! Finally, we did it! ([PR#61](https://github.com/sgrebnov/cordova-plugin-background-download/pull/61))

**Comment by toadeelali** [comment]
I added latest code in my app but no notification appeared need help.
