### ISSUE TITLE
Unsupported path android

### ISSUE THREAD

**Issue by Liestambeur** [sgrebnov/cordova-plugin-background-download#33]
Hey!

I'm trying to download a jpg file.
- it works on IOS
- on andoid I have an error: "Unsupported path /data/data/{app}/files/files/{id}.jpg.temp"

This is my code:

```
window.requestFileSystem(LocalFileSystem.PERSISTENT, 0, (fileSystem) => {
   fileSystem.root.getFile("${id}.jpg", {create: true, exclusive: true}, (targetFile) => {
     const url = "https://${process.env.API_ENDPOINT}/Preview/${id}";
      var downloader = new BackgroundTransfer.BackgroundDownloader();
      // Create a new download operation.
      var download = downloader.createDownload(url, targetFile);
      // Start the download and persist the promise to be able to cancel the download.
      download.startAsync().then(() => {
        //succes
      }, (error) => {
        console.log('onError', id, error);
      }, (progress) => {
        console.log('onProgress', id, progress);
      });
   });
});
```

The solution in #28 is not a good solution for me since it has to be stored on the internal storage of the application itself.

**Comment by KevRyan2** [comment]
same issue

**Comment by KevRyan2** [comment]
same issue here, continuing to try every configuration, if anyone has figured this out please provide the methods and file formats that end up working

**Comment by gkimpson** [comment]
I have the same issues? Did anyone find a fix for this? I am using cordova android@6.4.0 however will try a few versions to see if it works

**Comment by NickToropov** [comment]
Hi guys! We've made some improvements in this direction. Please update plugin and check if the issue has gone.

I'll close it for now but feel free to reopen it if you have any questions.

**Comment by hosseinzoda** [comment]
Installing at commit c5781c10d412241a7b6aaa384e9d2e4995941bb8 (master branch) did fix this error for me.
