### ISSUE TITLE
Change appearance of the 'Download Manager' when download is processing

### ISSUE THREAD

**Issue by gkimpson** [sgrebnov/cordova-plugin-background-download#44]
I have the background downloading process working and it appears to work well (on Android not tried iOS yet) however is it possible to alter the notification bar that appears?

Currently it has the title 'Download Manager' with `org.apache.cordova.backgroundDownload plugin' - is it possible to alter this easily?

**Comment by NickToropov** [comment]
Hi @gkimpson, thanks for you request! Yes, we finally did it. Please look at [PR#61](https://github.com/sgrebnov/cordova-plugin-background-download/pull/61).

I'll close this issue for now but feel free to reopen it if you have any questions with plugin.
