### ISSUE TITLE
For android, method CleanUp should be called in stop method

### ISSUE THREAD

**Issue by JoxC** [sgrebnov/cordova-plugin-background-download#59]
For android, method `CleanUp` should be called in `stop` method to remove activDownloads keys via `activDownloads.remove(curDownload.getUriString());`
otherwise, re-downloading the same url would not execute since activDownloads keys existence would be checked in startAsync method.

**Comment by sgrebnov** [comment]
Hi @JoxC thanks for reporting this; @NickToropov could you please take a look

**Comment by JoxC** [comment]
@sgrebnov @NickToropov Sorry, the issue was posted related to version 0.0.2 while the latest version 0.0.3 has a big difference with the previous one, and I have not yet read the code of the latest version. So you can close this issue if you wish.

**Comment by JoxC** [comment]
In the latest version clean up is called from startProgressTracking when stop task. So I will close this thread.
