### ISSUE TITLE
App crashes occationally on IOS with big files due to memory issue

### ISSUE THREAD

**Issue by punknroll** [sgrebnov/cordova-plugin-background-download#60]
Hi, the app crashes often when I try to download big files (>800 MB) on IOS. Xcode shows the following error:

Got memory pressure notification (critical)
Message from debugger: Terminated due to memory issue

Any hints to this? Thanks in advance.

**Comment by sgrebnov** [comment]
Could you please specify
1. plugin version - are you using the latest?
2. iOS/device version
3. Are you downloading single file or several? (concurrent download)

**Comment by punknroll** [comment]
Fail of the day:

ionic cordova plugin add installed another repo: https://github.com/rohitup/background-download

I use this one now and the problem is gone!
