### ISSUE TITLE
Can't supply headers to download request

### ISSUE THREAD

**Issue by greggarson** [sgrebnov/cordova-plugin-background-download#63]
I'd love to try out this plugin but it seems that you can't supply a list of headers to the plugin to be associated with the download request?  

Given cases where the download might be behind some kind of security wall this seems like a potentially useful addition?

Any plans on adding this in?

**Comment by Xatenev** [comment]
+1

**Comment by NickToropov** [comment]
Hi guys! At the moment we have no plans on adding this feature. But you are free to implement it and create a PR.
