### ISSUE TITLE
Update npm public package to latest version

### ISSUE THREAD

**Issue by curthusting** [sgrebnov/cordova-plugin-background-download#64]
The current available package on npm is 0.0.2 published a year ago. Do you have plans to update that to the current 0.5.0 release?

**Comment by NickToropov** [comment]
Hi @curthusting! we have no published versions in npm repository.
Please add our plugin as:
```
cordova plugin add https://github.com/sgrebnov/cordova-plugin-background-download.git
```
Let me know if you have any other questions.
