### ISSUE TITLE
Download fails on Android 13

### ISSUE THREAD

**Issue by mstrop** [sgrebnov/cordova-plugin-background-download#78]
All downloads fail with error message

Unsupported path /storage/emulated/0/ ......

Work with file system needs update.

**Comment by mstrop** [comment]
src/android/BackgroundDownload.java line 114 needs to be changed to 

this.setTempFileUri(Uri.fromFile(new File(android.os.Environment.getExternalStoragePublicDirectory(android.os.Environment.DIRECTORY_DOWNLOADS),
Uri.parse(targetFileUri).getLastPathSegment() + "." + System.currentTimeMillis())).toString());

**Comment by raubreak** [comment]
Works fine! thanks! 
*I needed to remove the Android platform and added it again to recompile the plugin, once edited from /plugins
